### ISSUE TITLE
Improvements for Editing Configurations: Select App Class from [...]

### ISSUE THREAD

**Issue by ahinchman1** [edvin/tornadofx-idea-plugin#60] opened 2018-05-21 00:49 UTC
Adding a function to be able to select the Application class:
<img width="942" alt="screen shot 2018-05-20 at 6 00 19 pm" src="https://user-images.githubusercontent.com/6917498/40285875-1f052b96-5c6f-11e8-9d38-e9fe0dae8680.png">

**Comment by edvin** [comment] 2018-05-22 08:19
I can't for the life of me figure out why the browser doesn't let us pick App classes, I've implemented the needed interface. It seems a lot of the configuration interfaces and properties have been deprecated, so I probably need to reimplement everything.

**Comment by SiebelsTim** [comment] 2018-08-06 15:25
I think this is a duplicate of #53

**Closed as completed by SiebelsTim** 2018-08-06 15:25 UTC

**Comment by edvin** [comment] 2018-08-06 15:28
Seems correct :)
