### ISSUE TITLE
Run configuration app class disappears on every IDE restart

### ISSUE THREAD

**Issue by jpd236** [edvin/tornadofx-idea-plugin#57] opened 2018-04-21 16:23 UTC
Every time I restart IntelliJ, the "App Class" field of my TornadoFX run configurations is blanked out, and I have to go reset them to the expected values before I can run anything.

Not sure how to provide more helpful info here - anything else I can share that would help you track this down?

Plugin version: 1.7.14.1 2018-02-01

IDE info:

IntelliJ IDEA 2018.1 (Community Edition)
Build #IC-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by edvin** [comment] 2018-04-23 07:41
I'm not able to reproduce myself. Do you have similar issues with other run configuration settings?

**Comment by jpd236** [comment] 2018-04-24 02:32
I have a bunch of JUnit rules which work after a restart. Interestingly, when I go to edit their configuration, it does highlight the selected test class as not being accessible, but then it runs fine.

This is a pure Kotlin/gradle project.

**Comment by edvin** [comment] 2018-04-24 06:28
OK, thanks for getting back to me. Not quite sure how to investigate this, but I'll leave this here for now to hear if others are experiencing the same issue. You don't get any stack traces in the IDE do you?

**Comment by jpd236** [comment] 2018-04-28 18:22
None I can see, and nothing obviously relevant in idea.log either, unfortunately.

I can reproduce it with the attached sample project, in case there's a subtle difference in what we're doing. I import it into IntelliJ, add the TornadoFX framework when prompted, open src/main/kotlin/example/Main.kt, run HelloWorldApp, and then close and reopen the project. Attached a screenshot of my import project settings as well.
[HelloWorldTornado.zip](https://github.com/edvin/tornadofx-idea-plugin/files/1958025/HelloWorldTornado.zip)
<img width="1074" alt="screen shot 2018-04-28 at 11 17 47 am" src="https://user-images.githubusercontent.com/4713321/39399646-6e2f1876-4ad6-11e8-9ff6-90355afa4d7a.png">

**Comment by edvin** [comment] 2018-04-30 08:29
I tested your project and the run configuration I make stays after closing and opening. You might want to try without Gradle and use Maven instead, in my experience IDEA support for Gradle is spotty.

**Comment by mstave** [comment] 2018-05-20 15:48
I am seeing this problem, too.  with a build.gradle with `mainClassName = "kgui.app.MyApp"` and `compile 'no.tornado:tornadofx:1.7.15'` and `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.41"`

**Comment by edvin** [comment] 2018-05-20 17:56
Can you guys check if an exception is thrown? Check the IDEA logs.

**Comment by jpd236** [comment] 2018-05-20 18:31
No exceptions or obvious errors that I can see. Attached logs from a shutdown + restart where the problem occurred.
[idea.log](https://github.com/edvin/tornadofx-idea-plugin/files/2020556/idea.log)

**Comment by edvin** [comment] 2018-05-22 08:20
OK, no clues there. Not sure how to attack this since I can't see the issue myself, but I'm going to implement parts of the run configuration because it seems that I'm using some deprecated functions, so we'll see if that resolves it.

**Comment by natschz** [comment] 2018-07-01 11:46
I'm seeing the same issue, I also noticed that the specified app class is not appearing in the configuration inside the workspace.xml:

```xml
    <configuration name="MyConfiguration" type="TORNADOFX_RUNCONFIGURATION" factoryName="TornadoFX Configuration Factory" run-type="App" live-views="false" live-stylesheets="false" dump-stylesheets="false">
      <module name="myModule" />
    </configuration>
```

Adding the main class option manually seems to work:
```xml
<option name="MAIN_CLASS_NAME" value="MainClass" />
```

**Comment by edvin** [comment] 2018-08-06 10:19
@SiebelsTim Since you're on a roll and obviously an IDEA plugin wizard - do you have time to look at this one? I think we're using a deprecated way of defining the run configuration, so it might be a matter of reimplementing it with to fit the new API.

**Comment by SiebelsTim** [comment] 2018-08-06 11:20
> IDEA plugin wizard

In reality, I have no idea what I'm doing. I'm just typing characters until something seems to be working.

I'll look at it :)

**Comment by edvin** [comment] 2018-08-06 11:21
This is how we all do it, Tim :) 😎

**Closed as completed** 2018-08-06 13:30 UTC
Labels: Status: In progress
